// Generates env service resolver dedicated for client side

"use strict";

const deferred     = require("deferred")
    , { resolve }  = require("path")
    , writeFile    = require("fs2/write-file")
		, debug        = require("debug")("setup")
    , autoprefixer = require("../lib/css-autoprefix-file")

    , rootPath = resolve(__dirname, "../../")
		, sourcePath = resolve(rootPath, "client/css")
    , targetPath = resolve(rootPath, "assets");

module.exports = async () => {
	debug("generate-css");

	const code = `/* DO NOT MODIFY FILE WAS AUTOGENERATED */

${ await autoprefixer(resolve(sourcePath, "style.css")) }`;

	return writeFile(resolve(targetPath, "style.css"), code, { intermediate: true });
};

if (require.main === module) deferred(module.exports()).done();
